insert into albums (id, title, artistid, url, image) values (1, 'White-nosed coatimundi', 46, 'http://yahoo.co.jp/ante/vestibulum/ante/ipsum.html', 'http://dummyimage.com/171x191.jpg/cc0000/ffffff');
insert into albums (id, title, artistid, url, image) values (2, 'Currasow (unidentified)', 7, 'http://cdc.gov/quam/sapien.js', 'http://dummyimage.com/196x221.jpg/5fa2dd/ffffff');
insert into albums (id, title, artistid, url, image) values (3, 'Great cormorant', 25, 'https://slideshare.net/proin.jpg', 'http://dummyimage.com/106x239.jpg/cc0000/ffffff');
insert into albums (id, title, artistid, url, image) values (4, 'Black spider monkey', 36, 'http://digg.com/nec/nisi/volutpat/eleifend/donec.xml', 'http://dummyimage.com/149x176.bmp/5fa2dd/ffffff');
insert into albums (id, title, artistid, url, image) values (5, 'Shrike, southern white-crowned', 5, 'https://quantcast.com/aliquet/massa/id.png', 'http://dummyimage.com/181x116.bmp/cc0000/ffffff');
insert into albums (id, title, artistid, url, image) values (6, 'Great egret', 4, 'http://google.es/volutpat/erat/quisque.xml', 'http://dummyimage.com/169x122.bmp/5fa2dd/ffffff');
insert into albums (id, title, artistid, url, image) values (7, 'Cormorant, pied', 21, 'http://symantec.com/leo/odio/porttitor/id.aspx', 'http://dummyimage.com/238x113.bmp/ff4444/ffffff');
insert into albums (id, title, artistid, url, image) values (8, 'Canadian river otter', 21, 'https://guardian.co.uk/nec/nisi/volutpat/eleifend/donec.jsp', 'http://dummyimage.com/125x239.jpg/dddddd/000000');
insert into albums (id, title, artistid, url, image) values (9, 'Crab (unidentified)', 43, 'http://statcounter.com/at/nibh/in/hac/habitasse/platea/dictumst.png', 'http://dummyimage.com/111x160.jpg/5fa2dd/ffffff');
insert into albums (id, title, artistid, url, image) values (10, 'Bobcat', 16, 'http://youku.com/interdum/eu/tincidunt.jsp', 'http://dummyimage.com/232x229.jpg/cc0000/ffffff');
insert into albums (id, title, artistid, url, image) values (11, 'Swan, black', 16, 'http://jigsy.com/leo/pellentesque/ultrices/mattis/odio/donec.js', 'http://dummyimage.com/206x148.bmp/5fa2dd/ffffff');
insert into albums (id, title, artistid, url, image) values (12, 'Opossum, american virginia', 38, 'https://fastcompany.com/eleifend.js', 'http://dummyimage.com/163x237.png/cc0000/ffffff');
insert into albums (id, title, artistid, url, image) values (13, 'Armadillo, nine-banded', 22, 'https://cafepress.com/sapien/quis/libero/nullam.png', 'http://dummyimage.com/135x229.bmp/5fa2dd/ffffff');
insert into albums (id, title, artistid, url, image) values (14, 'Common boubou shrike', 10, 'http://angelfire.com/magna/bibendum/imperdiet/nullam.aspx', 'http://dummyimage.com/179x173.bmp/cc0000/ffffff');
insert into albums (id, title, artistid, url, image) values (15, 'Black-tailed tree creeper', 25, 'http://mozilla.com/non/mattis/pulvinar/nulla.png', 'http://dummyimage.com/141x179.bmp/cc0000/ffffff');
insert into albums (id, title, artistid, url, image) values (16, 'Asiatic jackal', 4, 'http://bloglines.com/risus.jpg', 'http://dummyimage.com/140x113.png/cc0000/ffffff');
insert into albums (id, title, artistid, url, image) values (17, 'Kingfisher, white-throated', 10, 'http://com.com/urna/pretium/nisl/ut/volutpat/sapien.js', 'http://dummyimage.com/188x174.png/cc0000/ffffff');
insert into albums (id, title, artistid, url, image) values (18, 'Anaconda (unidentified)', 10, 'http://goo.ne.jp/leo/odio/porttitor.xml', 'http://dummyimage.com/137x187.png/5fa2dd/ffffff');
insert into albums (id, title, artistid, url, image) values (19, 'Waxbill, violet-eared', 42, 'http://hugedomains.com/sapien/ut.xml', 'http://dummyimage.com/238x116.png/dddddd/000000');
insert into albums (id, title, artistid, url, image) values (20, 'Francolin, swainson''s', 36, 'http://alexa.com/eget/orci.js', 'http://dummyimage.com/164x245.jpg/cc0000/ffffff');
insert into albums (id, title, artistid, url, image) values (21, 'Peregrine falcon', 4, 'https://gov.uk/sem/sed/sagittis.json', 'http://dummyimage.com/128x221.png/ff4444/ffffff');
insert into albums (id, title, artistid, url, image) values (22, 'Barking gecko', 22, 'http://latimes.com/ac/diam.json', 'http://dummyimage.com/129x156.png/ff4444/ffffff');
insert into albums (id, title, artistid, url, image) values (23, 'Lion, steller''s sea', 37, 'https://paypal.com/vestibulum/quam/sapien/varius.json', 'http://dummyimage.com/211x135.bmp/5fa2dd/ffffff');
insert into albums (id, title, artistid, url, image) values (24, 'Python, carpet', 35, 'http://pagesperso-orange.fr/in/sagittis/dui.aspx', 'http://dummyimage.com/108x178.bmp/dddddd/000000');
insert into albums (id, title, artistid, url, image) values (25, 'Tarantula, salmon pink bird eater', 20, 'https://topsy.com/porttitor/lorem/id/ligula/suspendisse/ornare.json', 'http://dummyimage.com/143x236.jpg/cc0000/ffffff');
insert into albums (id, title, artistid, url, image) values (26, 'African wild dog', 3, 'https://ebay.com/in/porttitor/pede/justo/eu/massa/donec.png', 'http://dummyimage.com/129x159.bmp/ff4444/ffffff');
insert into albums (id, title, artistid, url, image) values (27, 'Greater rhea', 15, 'http://mozilla.com/penatibus/et/magnis/dis/parturient.jsp', 'http://dummyimage.com/222x213.bmp/ff4444/ffffff');
insert into albums (id, title, artistid, url, image) values (28, 'Grenadier, common', 18, 'http://archive.org/eu/nibh/quisque/id/justo/sit.xml', 'http://dummyimage.com/154x108.bmp/dddddd/000000');
insert into albums (id, title, artistid, url, image) values (29, 'Vicuna', 19, 'http://last.fm/ultrices/erat.json', 'http://dummyimage.com/114x100.png/dddddd/000000');
insert into albums (id, title, artistid, url, image) values (30, 'Ring-tailed gecko', 40, 'https://soundcloud.com/non.aspx', 'http://dummyimage.com/240x191.bmp/5fa2dd/ffffff');
insert into albums (id, title, artistid, url, image) values (31, 'African bush squirrel', 25, 'http://cnet.com/lorem/id/ligula/suspendisse.jsp', 'http://dummyimage.com/153x248.png/ff4444/ffffff');
insert into albums (id, title, artistid, url, image) values (32, 'Civet (unidentified)', 27, 'https://hexun.com/mauris/morbi/non/lectus/aliquam.js', 'http://dummyimage.com/193x120.png/cc0000/ffffff');
insert into albums (id, title, artistid, url, image) values (33, 'Large-eared bushbaby', 24, 'http://pbs.org/pede/ullamcorper/augue/a/suscipit/nulla.xml', 'http://dummyimage.com/169x199.bmp/5fa2dd/ffffff');
insert into albums (id, title, artistid, url, image) values (34, 'Least chipmunk', 24, 'https://google.ca/dui/nec.json', 'http://dummyimage.com/190x167.png/ff4444/ffffff');
insert into albums (id, title, artistid, url, image) values (35, 'Rufous-collared sparrow', 40, 'https://smugmug.com/pede/posuere/nonummy/integer.jsp', 'http://dummyimage.com/169x170.png/5fa2dd/ffffff');
insert into albums (id, title, artistid, url, image) values (36, 'Australian spiny anteater', 37, 'https://usatoday.com/volutpat/erat/quisque.xml', 'http://dummyimage.com/121x111.bmp/cc0000/ffffff');
insert into albums (id, title, artistid, url, image) values (37, 'Wallaby, whip-tailed', 3, 'http://utexas.edu/rhoncus/dui/vel.xml', 'http://dummyimage.com/101x142.bmp/ff4444/ffffff');
insert into albums (id, title, artistid, url, image) values (38, 'White-winged dove', 35, 'https://hubpages.com/eget/eros/elementum/pellentesque/quisque/porta/volutpat.aspx', 'http://dummyimage.com/189x191.bmp/cc0000/ffffff');
insert into albums (id, title, artistid, url, image) values (39, 'Long-tailed skua', 47, 'https://rediff.com/ut/odio/cras/mi.jsp', 'http://dummyimage.com/179x231.jpg/ff4444/ffffff');
insert into albums (id, title, artistid, url, image) values (40, 'Hornbill, red-billed', 21, 'http://archive.org/mauris.js', 'http://dummyimage.com/242x128.jpg/ff4444/ffffff');
insert into albums (id, title, artistid, url, image) values (41, 'Small-clawed otter', 22, 'https://ihg.com/odio/condimentum.aspx', 'http://dummyimage.com/192x124.bmp/cc0000/ffffff');
insert into albums (id, title, artistid, url, image) values (42, 'Duck, comb', 17, 'https://joomla.org/at/vulputate/vitae/nisl/aenean.html', 'http://dummyimage.com/179x154.jpg/ff4444/ffffff');
insert into albums (id, title, artistid, url, image) values (43, 'Weeper capuchin', 27, 'https://mozilla.org/justo/nec.html', 'http://dummyimage.com/231x101.bmp/cc0000/ffffff');
insert into albums (id, title, artistid, url, image) values (44, 'Vulture, king', 10, 'http://wikimedia.org/volutpat/sapien/arcu/sed/augue/aliquam.xml', 'http://dummyimage.com/236x243.png/cc0000/ffffff');
insert into albums (id, title, artistid, url, image) values (45, 'Sarus crane', 6, 'https://infoseek.co.jp/aliquet.jpg', 'http://dummyimage.com/224x123.png/dddddd/000000');
insert into albums (id, title, artistid, url, image) values (46, 'Blue-tongued skink', 15, 'http://quantcast.com/mi.jsp', 'http://dummyimage.com/103x105.jpg/cc0000/ffffff');
insert into albums (id, title, artistid, url, image) values (47, 'Antechinus, brown', 1, 'https://github.com/non/ligula/pellentesque/ultrices.html', 'http://dummyimage.com/138x224.bmp/ff4444/ffffff');
insert into albums (id, title, artistid, url, image) values (48, 'Tortoise, burmese black mountain', 26, 'https://geocities.jp/nec/dui/luctus/rutrum.png', 'http://dummyimage.com/105x141.bmp/dddddd/000000');
insert into albums (id, title, artistid, url, image) values (49, 'Dove, ring', 36, 'http://xinhuanet.com/vulputate/luctus/cum/sociis/natoque.jsp', 'http://dummyimage.com/140x121.png/5fa2dd/ffffff');
insert into albums (id, title, artistid, url, image) values (50, 'Crimson-breasted shrike', 23, 'https://ihg.com/odio/curabitur/convallis/duis/consequat.html', 'http://dummyimage.com/202x205.bmp/cc0000/ffffff');
insert into albums (id, title, artistid, url, image) values (51, 'Turtle (unidentified)', 1, 'http://theguardian.com/posuere/cubilia/curae/donec.json', 'http://dummyimage.com/146x221.png/cc0000/ffffff');
insert into albums (id, title, artistid, url, image) values (52, 'American marten', 12, 'http://google.cn/sem/praesent/id.html', 'http://dummyimage.com/208x194.png/dddddd/000000');
insert into albums (id, title, artistid, url, image) values (53, 'Tiger snake', 42, 'https://wunderground.com/tempus/semper/est/quam/pharetra/magna/ac.jsp', 'http://dummyimage.com/169x112.png/cc0000/ffffff');
insert into albums (id, title, artistid, url, image) values (54, 'Flamingo, chilean', 37, 'http://360.cn/vitae/mattis/nibh/ligula/nec.js', 'http://dummyimage.com/241x122.bmp/dddddd/000000');
insert into albums (id, title, artistid, url, image) values (55, 'Tokay gecko', 5, 'http://addtoany.com/orci/luctus/et/ultrices/posuere/cubilia/curae.png', 'http://dummyimage.com/154x241.bmp/ff4444/ffffff');
insert into albums (id, title, artistid, url, image) values (56, 'Spotted deer', 19, 'https://stumbleupon.com/maecenas/tristique/est/et/tempus/semper.xml', 'http://dummyimage.com/196x238.png/5fa2dd/ffffff');
insert into albums (id, title, artistid, url, image) values (57, 'Mountain duck', 12, 'https://bigcartel.com/tempus/vivamus.xml', 'http://dummyimage.com/180x117.bmp/cc0000/ffffff');
insert into albums (id, title, artistid, url, image) values (58, 'Black-capped capuchin', 38, 'https://cnet.com/nunc/proin/at/turpis/a.jsp', 'http://dummyimage.com/123x230.jpg/dddddd/000000');
insert into albums (id, title, artistid, url, image) values (59, 'American buffalo', 9, 'http://youtube.com/proin/leo/odio.xml', 'http://dummyimage.com/167x216.png/5fa2dd/ffffff');
insert into albums (id, title, artistid, url, image) values (60, 'Dove, white-winged', 24, 'https://studiopress.com/ultrices/mattis/odio.aspx', 'http://dummyimage.com/238x108.png/dddddd/000000');
insert into albums (id, title, artistid, url, image) values (61, 'Striated heron', 44, 'https://lycos.com/ipsum/praesent/blandit/lacinia.html', 'http://dummyimage.com/136x249.bmp/dddddd/000000');
insert into albums (id, title, artistid, url, image) values (62, 'Indian giant squirrel', 35, 'http://springer.com/ac/nulla/sed/vel/enim.html', 'http://dummyimage.com/104x212.png/5fa2dd/ffffff');
insert into albums (id, title, artistid, url, image) values (63, 'Buttermilk snake', 48, 'https://123-reg.co.uk/viverra.jsp', 'http://dummyimage.com/211x134.jpg/ff4444/ffffff');
insert into albums (id, title, artistid, url, image) values (64, 'Cow, scottish highland', 17, 'http://microsoft.com/erat/fermentum/justo/nec/condimentum/neque.aspx', 'http://dummyimage.com/112x242.png/5fa2dd/ffffff');
insert into albums (id, title, artistid, url, image) values (65, 'Raven, cape', 7, 'https://engadget.com/nonummy/maecenas/tincidunt/lacus/at/velit.js', 'http://dummyimage.com/250x131.png/dddddd/000000');
insert into albums (id, title, artistid, url, image) values (66, 'Macaque, japanese', 30, 'http://t-online.de/diam/cras.json', 'http://dummyimage.com/237x168.bmp/ff4444/ffffff');
insert into albums (id, title, artistid, url, image) values (67, 'Kite, black', 6, 'http://tiny.cc/nunc.aspx', 'http://dummyimage.com/107x175.png/5fa2dd/ffffff');
insert into albums (id, title, artistid, url, image) values (68, 'Marshbird, brown and yellow', 17, 'http://chronoengine.com/nascetur/ridiculus/mus/vivamus/vestibulum/sagittis/sapien.jpg', 'http://dummyimage.com/124x176.png/5fa2dd/ffffff');
insert into albums (id, title, artistid, url, image) values (69, 'Steenbuck', 44, 'https://people.com.cn/condimentum.js', 'http://dummyimage.com/133x132.jpg/ff4444/ffffff');
insert into albums (id, title, artistid, url, image) values (70, 'Cape starling', 46, 'https://networkadvertising.org/in/lectus/pellentesque/at/nulla/suspendisse.json', 'http://dummyimage.com/249x196.png/ff4444/ffffff');
insert into albums (id, title, artistid, url, image) values (71, 'North American red fox', 30, 'https://fastcompany.com/nunc/viverra.png', 'http://dummyimage.com/198x242.png/5fa2dd/ffffff');
insert into albums (id, title, artistid, url, image) values (72, 'Blue shark', 37, 'https://army.mil/in/porttitor/pede.jpg', 'http://dummyimage.com/134x198.jpg/dddddd/000000');
insert into albums (id, title, artistid, url, image) values (73, 'Emerald-spotted wood dove', 22, 'https://cbslocal.com/natoque/penatibus/et/magnis/dis/parturient/montes.html', 'http://dummyimage.com/236x116.png/5fa2dd/ffffff');
insert into albums (id, title, artistid, url, image) values (74, 'Llama', 17, 'https://examiner.com/nulla/suscipit/ligula/in.jsp', 'http://dummyimage.com/157x188.png/ff4444/ffffff');
insert into albums (id, title, artistid, url, image) values (75, 'White-bellied sea eagle', 21, 'http://nature.com/pulvinar/sed/nisl/nunc/rhoncus.jpg', 'http://dummyimage.com/144x240.jpg/5fa2dd/ffffff');
insert into albums (id, title, artistid, url, image) values (76, 'Grey heron', 10, 'http://eventbrite.com/bibendum/imperdiet.jpg', 'http://dummyimage.com/204x173.bmp/ff4444/ffffff');
insert into albums (id, title, artistid, url, image) values (77, 'Yellow baboon', 31, 'https://nifty.com/duis/mattis/egestas/metus/aenean.xml', 'http://dummyimage.com/183x108.bmp/dddddd/000000');
insert into albums (id, title, artistid, url, image) values (78, 'Plains zebra', 10, 'http://answers.com/sollicitudin/ut/suscipit/a/feugiat/et.jsp', 'http://dummyimage.com/180x157.jpg/dddddd/000000');
insert into albums (id, title, artistid, url, image) values (79, 'Capuchin, white-fronted', 47, 'https://ed.gov/congue/vivamus/metus/arcu/adipiscing/molestie.html', 'http://dummyimage.com/231x204.bmp/ff4444/ffffff');
insert into albums (id, title, artistid, url, image) values (80, 'Long-necked turtle', 47, 'https://indiatimes.com/rhoncus/aliquet/pulvinar/sed/nisl/nunc/rhoncus.xml', 'http://dummyimage.com/170x179.bmp/cc0000/ffffff');
insert into albums (id, title, artistid, url, image) values (81, 'Brown pelican', 18, 'http://ted.com/tincidunt/in/leo/maecenas.xml', 'http://dummyimage.com/224x244.png/cc0000/ffffff');
insert into albums (id, title, artistid, url, image) values (82, 'Hen, sage', 11, 'http://wikia.com/non.xml', 'http://dummyimage.com/148x128.png/dddddd/000000');
insert into albums (id, title, artistid, url, image) values (83, 'Kafue flats lechwe', 49, 'https://nhs.uk/tristique/est.aspx', 'http://dummyimage.com/131x211.png/cc0000/ffffff');
insert into albums (id, title, artistid, url, image) values (84, 'Caracara (unidentified)', 1, 'https://nydailynews.com/libero/convallis/eget/eleifend.json', 'http://dummyimage.com/141x249.png/5fa2dd/ffffff');
insert into albums (id, title, artistid, url, image) values (85, 'Opossum, american virginia', 14, 'https://ovh.net/sed/tristique/in/tempus/sit/amet.js', 'http://dummyimage.com/228x227.png/ff4444/ffffff');
insert into albums (id, title, artistid, url, image) values (86, 'Collared peccary', 28, 'https://ameblo.jp/feugiat/non/pretium.jpg', 'http://dummyimage.com/149x179.bmp/dddddd/000000');
insert into albums (id, title, artistid, url, image) values (87, 'Skunk, western spotted', 35, 'http://ycombinator.com/nec/sem/duis/aliquam/convallis/nunc/proin.aspx', 'http://dummyimage.com/236x156.jpg/dddddd/000000');
insert into albums (id, title, artistid, url, image) values (88, 'Pampa gray fox', 18, 'http://umn.edu/sapien/in/sapien/iaculis/congue.jpg', 'http://dummyimage.com/115x146.jpg/ff4444/ffffff');
insert into albums (id, title, artistid, url, image) values (89, 'Warthog', 12, 'https://gov.uk/curae.jpg', 'http://dummyimage.com/143x171.bmp/cc0000/ffffff');
insert into albums (id, title, artistid, url, image) values (90, 'Otter, small-clawed', 41, 'https://wikipedia.org/nascetur/ridiculus/mus.jpg', 'http://dummyimage.com/186x184.png/dddddd/000000');
insert into albums (id, title, artistid, url, image) values (91, 'Lapwing (unidentified)', 2, 'https://weebly.com/quisque/erat/eros/viverra.js', 'http://dummyimage.com/165x127.jpg/dddddd/000000');
insert into albums (id, title, artistid, url, image) values (92, 'Brazilian tapir', 15, 'http://kickstarter.com/congue/vivamus/metus.jsp', 'http://dummyimage.com/187x166.png/ff4444/ffffff');
insert into albums (id, title, artistid, url, image) values (93, 'Fox, crab-eating', 42, 'http://house.gov/dolor/morbi/vel/lectus/in.js', 'http://dummyimage.com/232x138.png/dddddd/000000');
insert into albums (id, title, artistid, url, image) values (94, 'Madagascar fruit bat', 36, 'http://springer.com/ipsum/primis.jsp', 'http://dummyimage.com/150x219.bmp/cc0000/ffffff');
insert into albums (id, title, artistid, url, image) values (95, 'Lechwe, kafue flats', 34, 'http://sciencedirect.com/id/massa/id/nisl.jpg', 'http://dummyimage.com/138x105.png/ff4444/ffffff');
insert into albums (id, title, artistid, url, image) values (96, 'Galapagos mockingbird', 1, 'http://huffingtonpost.com/at/nulla/suspendisse/potenti/cras.html', 'http://dummyimage.com/158x203.bmp/cc0000/ffffff');
insert into albums (id, title, artistid, url, image) values (97, 'Southern screamer', 14, 'https://wordpress.org/id/luctus/nec/molestie/sed/justo/pellentesque.xml', 'http://dummyimage.com/108x135.png/5fa2dd/ffffff');
insert into albums (id, title, artistid, url, image) values (98, 'Galapagos penguin', 1, 'https://mozilla.com/iaculis/justo.html', 'http://dummyimage.com/225x240.png/5fa2dd/ffffff');
insert into albums (id, title, artistid, url, image) values (99, 'Squirrel glider', 27, 'http://hc360.com/ac/diam/cras/pellentesque.jsp', 'http://dummyimage.com/148x142.png/dddddd/000000');
insert into albums (id, title, artistid, url, image) values (100, 'Crane, black-crowned', 10, 'https://uol.com.br/duis.json', 'http://dummyimage.com/141x155.bmp/dddddd/000000');
